version: '3'
services:
    app:
        build:
            dockerfile: ./docker/app.Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        networks:
            - laravel-net
    database:
        container_name: database
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        depends_on:
            - app
        networks:
            - laravel-net

#Docker Networks
networks:
    laravel-net:
        driver: bridge

volumes:
    db-data: ~