version: '3'
services:
    app:
        build:
            dockerfile: .
        container_name: app
        restart: unless-stopped
        tty: true
        volumes:
            - web-data:/var/www
        networks:
            - laravel-net
    database:
        container_name: database
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=default
            - MYSQL_USER=secret
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - db-data:/var/lib/mysql
    nginx:
        build:
            dockerfile: ./docker/nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        depends_on:
            - app
        volumes:
            - web-data:/var/www
        networks:
            - laravel-net

#Docker Networks
networks:
    laravel-net:
        driver: bridge

volumes:
    web-data: ~
    db-data: ~